---
# Playbook: deploy-k8s-manifests.yml
- name: Deploy Kubernetes manifests on selected VMs
  hosts: k8s_hosts
  become: yes
  vars:
    # Override with --extra-vars k8s_template=<filename>
    k8s_template: nginx-deployment.yaml
  tasks:
    - name: Copy Kubernetes manifest file to remote host
      copy:
        src: "{{ lookup('env','REPO_ROOT') }}/kubernetes/templates/{{ k8s_template }}"
        dest: /tmp/k8s-manifest.yaml

    - name: Apply Kubernetes manifest
      community.kubernetes.k8s:
        state: present
        src: /tmp/k8s-manifest.yaml
      register: k8s_result

    - name: Report Kubernetes deployment status
      debug:
        msg: "Kubernetes resources deployed: {{ k8s_result }}"
