---
# Playbook: deploy-docker-containers.yml
- name: Deploy Docker containers on selected VMs
  hosts: docker_hosts
  become: yes
  vars:
    # Override with --extra-vars docker_template=<filename>
    docker_template: nginx-container.yml
  tasks:
    - name: Ensure Docker SDK for Python is installed
      pip:
        name: docker
      when: ansible_pkg_mgr == 'pip'

    - name: Copy Docker Compose file to remote host
      copy:
        src: "{{ lookup('env','REPO_ROOT') }}/docker/templates/{{ docker_template }}"
        dest: /tmp/docker-compose.yml

    - name: Start Docker Compose services
      community.docker.docker_compose:
        project_src: /tmp
        files:
          - docker-compose.yml
        state: present
      register: compose_result

    - name: Report deployment status
      debug:
        msg: "Docker containers deployed: {{ compose_result }}"
