---
- name: Install Security Tools
  hosts: "{{ target_hosts | default('template_vms') }}"
  become: true
  tasks:
    - name: Install fail2ban
      apt:
        name: fail2ban
        state: present
    - name: Install rkhunter
      apt:
        name: rkhunter
        state: present
    - name: Install clamav
      apt:
        name: clamav
        state: present
