---
- name: Install Monitoring Tools
  hosts: "{{ target_hosts | default('template_vms') }}"
  become: true
  tasks:
    - name: Install Prometheus Node Exporter
      apt:
        name: prometheus-node-exporter
        state: present
    - name: Install Telegraf
      apt:
        name: telegraf
        state: present
