---
- name: Install Kubernetes Tools on Template VMs
  hosts: "{{ target_hosts | default('template_vms') }}"
  become: true
  vars:
    kubernetes_version: "1.29"
    kubectl_version: "{{ kubernetes_version }}"
    helm_version: "3.14.0"
    k9s_version: "0.31.7"

  tasks:
    - name: Add Kubernetes apt repository key
      apt_key:
        url: https://pkgs.k8s.io/core:/stable:/v{{ kubernetes_version }}/deb/Release.key
        keyring: /etc/apt/keyrings/kubernetes-apt-keyring.gpg
        state: present

    - name: Add Kubernetes apt repository
      apt_repository:
        repo: >-
          deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg]
          https://pkgs.k8s.io/core:/stable:/v{{ kubernetes_version }}/deb/ /
        state: present
        update_cache: true

    - name: Install kubectl
      apt:
        name: kubectl={{ kubectl_version }}.*
        state: present
        allow_downgrade: true

    - name: Hold kubectl package
      dpkg_selections:
        name: kubectl
        selection: hold

    - name: Download and install Helm
      unarchive:
        src: https://get.helm.sh/helm-v{{ helm_version }}-linux-amd64.tar.gz
        dest: /tmp
        remote_src: true
        creates: /tmp/linux-amd64/helm

    - name: Move Helm binary to PATH
      copy:
        src: /tmp/linux-amd64/helm
        dest: /usr/local/bin/helm
        mode: "0755"
        remote_src: true

    - name: Download and install k9s
      get_url:
        url: https://github.com/derailed/k9s/releases/download/v{{ k9s_version }}/k9s_Linux_amd64.tar.gz
        dest: /tmp/k9s.tar.gz

    - name: Extract k9s
      unarchive:
        src: /tmp/k9s.tar.gz
        dest: /tmp
        remote_src: true

    - name: Move k9s binary to PATH
      copy:
        src: /tmp/k9s
        dest: /usr/local/bin/k9s
        mode: "0755"
        remote_src: true

    - name: Create kubectl completion script
      shell: kubectl completion bash > /etc/bash_completion.d/kubectl
      args:
        creates: /etc/bash_completion.d/kubectl

    - name: Create helm completion script
      shell: helm completion bash > /etc/bash_completion.d/helm
      args:
        creates: /etc/bash_completion.d/helm

    - name: Clean up temporary files
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - /tmp/linux-amd64
        - /tmp/k9s.tar.gz
        - /tmp/k9s
        - /tmp/LICENSE
        - /tmp/README.md
