---
# Playbook: update-all-packages.yml
- name: Update all packages on all VMs
  hosts: all
  become: yes
  tasks:
    - name: Update apt packages
      apt:
        update_cache: yes
        upgrade: dist
      when: ansible_pkg_mgr == 'apt'

    - name: Update yum/dnf packages
      yum:
        name: "*"
        state: latest
      when: ansible_pkg_mgr in ['yum','dnf']

    - name: Update zypper packages
      zypper:
        name: "*"
        state: latest
      when: ansible_pkg_mgr == 'zypper'

    - name: Update pacman packages
      pacman:
        upgrade: yes
      when: ansible_pkg_mgr == 'pacman'

    - name: Update xbps packages
      command: xbps-install -Su
      when: ansible_pkg_mgr == 'xbps-install'

    - name: Update Gentoo emerge world
      command: emerge --update --deep --with-bdeps=y @world
      when: ansible_pkg_mgr == 'emerge'

    - name: Update NixOS system
      command: nixos-rebuild switch --upgrade
      when: ansible_pkg_mgr == 'nix'
